export enum ResultCode {
	OK,
	INTERNAL_ERROR,
	USER_NOT_FOUND,
	LOGIN_IS_IN_USE,
	WRONG_PASSWORD,
	INVALID_BODY,
	TOKEN_REQUIRED,
	CONNECTION_ERROR,
	FILE_TOO_LARGE,
	FILE_TYPE_UNSUPPORTED,
	FILE_UPLOAD_ABORTED
}
